version: '3'
services:
  apache-service:
    container_name: server
    image: 'httpd:latest'
    ports:
      - '99:80'
    volumes:
      - ./Website:/usr/local/apache2/htdocs

  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '7000:7005'

  db:
    container_name: mysql
    image: 'mysql'
    ports:
      - '9000:9050'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
